// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6SbxsrJm33ba7_qajbDvzYUjod8CmO8',
    appId: '1:169343509253:web:83b44e8b12ab9c8bd78d6c',
    messagingSenderId: '169343509253',
    projectId: 'levelx-test-project',
    authDomain: 'levelx-test-project.firebaseapp.com',
    storageBucket: 'levelx-test-project.appspot.com',
    measurementId: 'G-LVC3Y8CXJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCFAyW3hmmi2Qoh40k7gstMseiDES6EVY',
    appId: '1:169343509253:android:f456c72caeaac736d78d6c',
    messagingSenderId: '169343509253',
    projectId: 'levelx-test-project',
    storageBucket: 'levelx-test-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkRLNg1JkZonHDbPIKwYAUst_KG79jvs',
    appId: '1:169343509253:ios:5456d2e364dd224ad78d6c',
    messagingSenderId: '169343509253',
    projectId: 'levelx-test-project',
    storageBucket: 'levelx-test-project.appspot.com',
    androidClientId: '169343509253-gt8hmctle8bpjie4tjeouh6uiql6edmh.apps.googleusercontent.com',
    iosClientId: '169343509253-57i1aqvkigfn9sedu7s1eq1j5flih5rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAkRLNg1JkZonHDbPIKwYAUst_KG79jvs',
    appId: '1:169343509253:ios:5456d2e364dd224ad78d6c',
    messagingSenderId: '169343509253',
    projectId: 'levelx-test-project',
    storageBucket: 'levelx-test-project.appspot.com',
    androidClientId: '169343509253-gt8hmctle8bpjie4tjeouh6uiql6edmh.apps.googleusercontent.com',
    iosClientId: '169343509253-57i1aqvkigfn9sedu7s1eq1j5flih5rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
